/* eslint-disable no-shadow */
/* eslint-disable no-param-reassign */
/* eslint-disable no-mixed-operators, no-bitwise */
/* global localStorage */
import moment from 'moment';
import qs from 'querystring';
import compact from 'lodash/compact';
import every from 'lodash/every';
import filter from 'lodash/filter';
import find from 'lodash/find';
import findKey from 'lodash/findKey';
import forEach from 'lodash/forEach';
import get from 'lodash/get';
import has from 'lodash/has';
import identity from 'lodash/identity';
import inRange from 'lodash/inRange';
import isArray from 'lodash/isArray';
import isEmpty from 'lodash/isEmpty';
import isEqual from 'lodash/isEqual';
import isNumber from 'lodash/isNumber';
import isString from 'lodash/isString';
import includes from 'lodash/includes';
import join from 'lodash/join';
import last from 'lodash/last';
import map from 'lodash/map';
import set from 'lodash/set';
import pick from 'lodash/pick';
import pickBy from 'lodash/pickBy';
import range from 'lodash/range';
import replace from 'lodash/replace';
import split from 'lodash/split';
import times from 'lodash/times';
import toString from 'lodash/toString';
import toNumber from 'lodash/toNumber';
import size from 'lodash/size';
import values from 'lodash/values';
